### ISSUE TITLE
Error with Default Configs in Orb federacy/salus@3.0.0

### ISSUE THREAD

**Issue by CoinsNaulty** [coinbase/salus#384]
**Description**
Running into issue with default usage of Salus CircleCI Orb.

**Versions**
- CircleCI Orb:`federacy/salus@3.0.0`
- Docker: `coinbase/salus@sha256:8ed3483526f17aa90745b322839465803b86064501d08dda1589ada303c471bb`

**Error Message**
`Could not send Salus report: (StandardError: Local report uri /home/repo/../salus-report.json should be relative to repo path and cannot have invalid chars)`

**Expected results**
- Run [Example](https://github.com/coinbase/salus/blob/9cd697036bed96c7acd17add04d7b87d56c9b93a/integrations/circleci/README.md#blocking-scan-with-all-scanners) setup and receive uploaded artifact

**Actual Results**
- Received Error Message referenced above ^^

**Related Info**

It looks like the current default path is not meant to work, based on this [commit](https://github.com/coinbase/salus/commit/2af04943f950cc34b9d08fb53bff923c81a1ad4f#diff-37b590943f91976f0f06a2dd8c5b429476443afde906e871abd2424c924ca35dR216) and [test condition](https://github.com/coinbase/salus/commit/2af04943f950cc34b9d08fb53bff923c81a1ad4f#diff-f04932072b9638aa3236cef27893f6835c5bd987758929d2ee95dbf4c0928858R81)

**Workarounds**

I tweaked [this section](https://github.com/coinbase/salus/blob/9cd697036bed96c7acd17add04d7b87d56c9b93a/integrations/circleci/orb.yml#L10-L94) of the orb.yml job and had the `storage_artifact` consume the remote_uri filename parameter

**Comment by jnaulty** [comment]
Fixed by #385

**Comment by ghbren** [comment]
closing ticket because PR has been merged.
