### ISSUE TITLE
Bundler 2 Errors

### ISSUE THREAD

**Issue by nishils** [coinbase/salus#43]
This is for anybody else that runs into this issue.

```
bundler: failed to load command: ./bin/salus (./bin/salus)
Bundler::LockfileError: You must use Bundler 2 or greater with this lockfile.
```

Currently, Salus does not support Gemfiles produced by Bundler 2.x.x. The workaround is to re-bundle your application with Bundler 1.x.x. You can see which bundler you are running with bundler -v or by checking the Gemfile.lock file to see which bundler version produced the Gemfile.lock

**Comment by jborrey** [comment]
@nishils Can you explain the issue more? I don't really understand why this error is happening.
