### ISSUE TITLE
Interest in adding ruby_audit to the list of scanners?

### ISSUE THREAD

**Issue by colinxfleming** [coinbase/salus#56]
hey! 👋 this is a neat idea and a pretty cool project. 

I was looking thru the ruby stuff and saw that you had bundler-audit in there, which rules. I thought I'd suggest adding a similar library that checks for ruby language vulnerabilities, which get flagged reasonably frequently. The library in question is over here: https://github.com/civisanalytics/ruby_audit we've been using it at @DCAFEngineering for awhile and it's worked pretty well for us.

I'm more than happy to take a crack at this if this sounds useful, figured I would check first. Let me know!

**Comment by nishils** [comment]
Hey @colinxfleming,

Great question. I am looking into the differences between the bundler-audit and ruby_audit. It seems as though that ruby_audit finds CVEs in Ruby itself whereas bundler_audit finds CVEs on gems. 

Let me know if I am misunderstanding.

Thanks!

**Comment by colinxfleming** [comment]
@nishils yeah, that's exactly right -- we're using ruby-audit to fail builds if it finds CVEs in the version of ruby we're using. Is that something that sounds like it might be useful to add?

**Comment by jsulinski** [comment]
This would be great and we would definitely use it!

**Comment by nishils** [comment]
Yes, this would be awesome! Definitely take a look at how the bundler scanner gets setup and the pattern should be similar.

Let me know what you may need help with.

**Comment by colinxfleming** [comment]
hey, a quick update now that I've had time to check this out and figure out where the trouble spots are: Plugging in the ruby_audit library wasn't too bad, but it appears to be reading from the (active ruby version)[https://github.com/civisanalytics/ruby_audit/blob/master/lib/ruby_audit/scanner.rb#L29] (and rubygems), rather than what's declared in the gemfile, like (I think bundler-audit is)[https://github.com/rubysec/bundler-audit/blob/master/lib/bundler/audit/scanner.rb#L42].

Since this runs within the context of a docker container, I think that means it'll really be scanning the docker container for ruby and rubygems vulns rather than the lockfile, making it sorta useless. (Useful warnings about rubygems are probably out of the question more generally, since as far as I know there isn't a way to get that to show up anywhere except `gem --version`. That's a bummer.)

I might submit a patch to ruby_audit to add an option to scan the lockfile rather than use `RUBY_VERSION` because I think it would be useful. But that means this issue isn't exactly heading for a speedy resolution, haha.

If you want to keep the issues list clean, you can probably close this out without action, since to do this it would take some work outside of this codebase. Apologies for the false start on this!

A commit with my changes (up until the point when I was like 'uh oh' and came here to post) is here: https://github.com/colinxfleming/salus/tree/add-ruby-audit

**Comment by nishils** [comment]
Sorry this is late but is there an issue open upstream? I'd like to get it linked here so we can watch for any updates upstream.

**Comment by colinxfleming** [comment]
oh yeah for sure! I added an issue to bundler here but it hasn't gotten any attention yet: https://github.com/bundler/bundler/issues/7194 

I could have sworn I added an issue in ruby_audit but looks like I did not, my bad. I'll do that tmrw.

**Comment by colinxfleming** [comment]
Opened an issue in ruby_audit at https://github.com/civisanalytics/ruby_audit/issues/10

If we resolve the ruby_audit issue then we can check ruby version, but we'd have to bump the bundler issue and then bump ruby_audit again to resolve the rubygems issue. Still, now we know the path forward?

**Comment by colinxfleming** [comment]
hey, doing a quick base-touch on this - state of the world hasn't really changed. There's still not a ~ reliable ~ way to include ruby version or rubygems version in Gemfile.lock (as noted in https://github.com/civisanalytics/ruby_audit/issues/10 ).

I don't expect to see much love on the issue opened in bundler, so I'd say if you want to keep your issues list clean here you're welcome to close this as a wontfix. (Or we can leave it open and see what happens!) Up to you all, I'm chill with it either way.

**Comment by xolaz** [comment]
thank you for following up @colinxfleming ! We'll close this for now, open to revisiting in the future 🎉 .
