### ISSUE TITLE
Adding a new scanner checklist

### ISSUE THREAD

**Issue by nishils** [coinbase/salus#58]
Provide a checklist of what every scanner should support in terms of integrating with Salus.

This can include things like 

- please write tests
- please add documentation in the salus docs folder
- please document config in the salus docs folder.

This will make sure that scanners are consistent and make it easier for folks to contribute.

**Comment by jborrey** [comment]
+1

**Comment by kiwiz** [comment]
Hi, looking to contribute and it'd be great if this checklist was completed for referenc.

**Comment by nishils** [comment]
I'm actually about to start working on a custom scanner so I can create a first draft here in the next day or two.

**Comment by nishils** [comment]
@kiwiz - Opened a PR for this. If you'd like to take a look and provide feedback on anything confusing or unclear, it would be greatly appreciated.
