### ISSUE TITLE
Update dependency CVE databases before each run

### ISSUE THREAD

**Issue by nishils** [coinbase/salus#60]
Run `bundle audit check --update` to update ruby cve db without having to rebuild container.

We should look into being able to do this for npm and yarn so the db isn't tied to when the docker container is built.

**Comment by jborrey** [comment]
+1

**Comment by nishils** [comment]
I am blind as a bat. This was never an issue.

See https://github.com/coinbase/salus/blob/master/lib/salus/scanners/bundle_audit.rb#L13
