### ISSUE TITLE
--config parameter doesn't work

### ISSUE THREAD

**Issue by GMartinez-Sisti** [coinbase/salus#72]
The config parameter is not being parsed correctly. I've read all the documentation multiple times and even check the code, but I can't found the problem.

This is an example where I rename the default config and then try to load the new file, I've also tried appending without removing, but the new files are never loaded and there is no complain:

```sh
→ docker run --rm -it --entrypoint=bash -v $(pwd):/home/repo coinbase/salus:2.6.1
root@cc58caacc33b:/home# mv salus-default.yaml salus-default-new.yaml
root@cc58caacc33b:/home# bundle exec /home/bin/salus scan --config "file://salus-default-new.yaml"
bundler: failed to load command: /home/bin/salus (/home/bin/salus)
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/lib/salus/../../salus-default.yaml
  /home/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `initialize'
  /home/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
  /home/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
  /home/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.5/lib/safe_yaml.rb:33:in `safe_load_file'
  /home/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.5/lib/safe_yaml.rb:22:in `load_file_with_options'
  /home/lib/salus/config.rb:29:in `<class:Config>'
  /home/lib/salus/config.rb:5:in `<module:Salus>'
  /home/lib/salus/config.rb:4:in `<top (required)>'
  /home/lib/salus.rb:18:in `require'
  /home/lib/salus.rb:18:in `<top (required)>'
  /home/bin/salus:6:in `require'
  /home/bin/salus:6:in `<top (required)>'
root@cc58caacc33b:/home# ls salus-default-new.yaml
salus-default-new.yaml
```

Am I doing something wrong, or is this a bug?

Thanks

**Comment by nishils** [comment]
Thanks for reporting!

1. Were you trying to open bash as a debugging step or were you trying to start salus this way?

We have been running with config without issues.

Have you tried running inside the home directory of your project? I just tried this locally and it seems to work.

docker run -t -v $(pwd):/home/repo coinbase/salus:2.6.1 --config "file://./salus-default-new.yaml"

**Comment by nishils** [comment]
I was able to replicate the issue so taking a look at what is happening

**Comment by nishils** [comment]
Oh you are moving the file. Salus assumes there is always a salus-default.yaml file. No need to touch this.

Salus automatically overrides the relevant defaults with any specified yaml file. So, if you do a copy instead of a rename and modify the new file. The new settings will be respected.

**Comment by nishils** [comment]
See https://github.com/coinbase/salus/blob/0ac45f3137ffde3fb1be0971b7359945d276b9f4/lib/salus/config.rb#L42 for how this gets parsed if you are curious.

**Comment by nishils** [comment]
Have you seen the docs located at https://github.com/coinbase/salus/blob/master/docs/configuration.md#providing-configuration-to-salus?

This should help clear up any confusion!

**Comment by GMartinez-Sisti** [comment]
Hi @nishils, thank you for helping.

Please note that I already tried to add a configuration with the steps in your documentation. But the file is ignored.

Here is an example of this. Check that the scanners still run even when I configure them not to on the custom config file:

```sh
root@338726d45cbb:/home# bundle exec /home/bin/salus scan
[INFORMATIONAL: 2019-08-31 19:02:25 +0000]: Salus is running.
==== Salus Scan v2.6.1

Overall scan status: FAILED in 1.24s

┌───────────────────┬──────────────┬──────────┬────────┐
│ Scanner           │ Running Time │ Required │ Passed │
├───────────────────┼──────────────┼──────────┼────────┤
│ YarnAudit         │ 1.08s        │ yes      │ no     │
│ PatternSearch     │ 0.0s         │ yes      │ yes    │
│ RepoNotEmpty      │ 0.01s        │ yes      │ yes    │
│ ReportNodeModules │ 0.14s        │ no       │ yes    │
└───────────────────┴──────────────┴──────────┴────────┘

==== YarnAudit: FAILED in 1.08s

 ~~ Scanner Logs:

  [...]

==== PatternSearch: PASSED in 0.0s

==== RepoNotEmpty: PASSED in 0.01s

==== ReportNodeModules: PASSED in 0.14s


root@338726d45cbb:/home# cat a.yaml
---
active_scanners: none


root@338726d45cbb:/home# bundle exec /home/bin/salus scan --config file://a.yaml
[INFORMATIONAL: 2019-08-31 19:02:41 +0000]: Salus is running.
==== Salus Scan v2.6.1

Overall scan status: FAILED in 1.29s

┌───────────────────┬──────────────┬──────────┬────────┐
│ Scanner           │ Running Time │ Required │ Passed │
├───────────────────┼──────────────┼──────────┼────────┤
│ YarnAudit         │ 1.13s        │ yes      │ no     │
│ PatternSearch     │ 0.0s         │ yes      │ yes    │
│ RepoNotEmpty      │ 0.01s        │ yes      │ yes    │
│ ReportNodeModules │ 0.14s        │ no       │ yes    │
└───────────────────┴──────────────┴──────────┴────────┘

==== YarnAudit: FAILED in 1.13s

 ~~ Scanner Logs:

  [...]

==== PatternSearch: PASSED in 0.0s

==== RepoNotEmpty: PASSED in 0.01s

==== ReportNodeModules: PASSED in 0.14s
root@338726d45cbb:/home#
```

**Comment by nishils** [comment]
Is there a reason you are trying to run salus from within the container?

The --config flag is meant to be appended when running the Salus docker container from the host machine and not from within the container.

**Comment by nishils** [comment]
This is the command you want.

`docker run --rm -v $(pwd):/home/repo coinbase/salus --config file://tests/salus-config.yaml`

Note how the config file is passed during the docker run command. *There should be no need to go inside the container and run bundle exec.*

**Comment by GMartinez-Sisti** [comment]
@nishils I'm testing this way because we are calling Salus from another script in the CI pipeline, since we are already in a docker container we can't start another container in the job.

I don't see why this is not working since we are running the same command specified in the entrypoint `ENTRYPOINT ["bundle", "exec", "./bin/salus", "scan"` ([here](https://github.com/coinbase/salus/blob/master/Dockerfile#L92")).

Looks like this a specific problem for us only, so you can close if you want.

**Comment by nishils** [comment]
I see what you are trying to do. This is not common but should still work.

Using just a salus.yaml file in the root target directory, the settings are respected.

```
root@d76a46fe074b:/home# cat repo/salus.yaml
active_scanners: none
root@d76a46fe074b:/home# bundle exec ./bin/salus scan
[INFORMATIONAL: 2019-09-02 19:56:18 +0000]: Salus is running.
==== Salus Scan v2.6.1

Overall scan status: PASSED in 0.0s

┌─────────┬──────────────┬──────────┬────────┐
│ Scanner │ Running Time │ Required │ Passed │
├─────────┼──────────────┼──────────┼────────┤

└─────────┴──────────────┴──────────┴────────┘
root@d76a46fe074b:/home#

```

Let me see what the exact syntax is for a file with a different naming convention.

**Comment by nishils** [comment]
Note that `/home/` is where the Salus scanner files are located and that `/home/repo` is where the project to be scanned is located. Let's call this the target repo.

Scenario 1: Salus config file is located in the target repo.
```
root@e3b1f033695f:/home# cat repo/salus-config.yaml
active_scanners: none
root@e3b1f033695f:/home# bundle exec ./bin/salus scan --config="file://salus-config.yaml"
[INFORMATIONAL: 2019-09-02 20:03:25 +0000]: Salus is running.
==== Salus Scan v2.6.1

Overall scan status: PASSED in 0.0s

┌─────────┬──────────────┬──────────┬────────┐
│ Scanner │ Running Time │ Required │ Passed │
├─────────┼──────────────┼──────────┼────────┤

└─────────┴──────────────┴──────────┴────────┘
```

Scenario 2: Salus config file is located in root.
```
root@e3b1f033695f:/home# bundle exec ./bin/salus scan --config="file://../../salus-config.yaml"
[INFORMATIONAL: 2019-09-02 20:07:00 +0000]: Salus is running.
==== Salus Scan v2.6.1

Overall scan status: PASSED in 0.0s

┌─────────┬──────────────┬──────────┬────────┐
│ Scanner │ Running Time │ Required │ Passed │
├─────────┼──────────────┼──────────┼────────┤

└─────────┴──────────────┴──────────┴────────┘
```

**Comment by nishils** [comment]
At least initial thoughts, it would be nice if Salus surfaced some warning information that it couldn't find the configuration file. Would that be helpful?

**Comment by nishils** [comment]
Also, you were running the command incorrectly. If you run `bundle exec ./bin/salus` or `bundle exec ./bin/salus help`, salus gives you the command line documentation.

**Comment by GMartinez-Sisti** [comment]
:O I didnt' know the `=` was needed. Thanks for the help :) I can confirm it works! Also I didn't know that the file was relative to /home, usually it's relative to where we are calling the command, or you can send the full path to ensure it's correct.

Regarding the parameter, I was trying what is specified here: https://github.com/coinbase/salus/blob/master/docs/configuration.md

> --config file://tests/salus-config.yaml

From within it says:

```sh
root@16f932d54825:/home# bundle exec ./bin/salus help
Commands:
  salus help [COMMAND]  # Describe available commands or one specific command
  salus scan            # Scan the source code of a repository.

Options:
  -c, [--config=CONFIG]                # Point to local or remote configuration files. e.g. --config="file path/to/salus.yaml"
  -q, [--quiet], [--no-quiet]          # Do not print reports to STDOUT.
  -v, [--verbose], [--no-verbose]      # Include "info" level data in reports printed to STDOUT.
  -d, [--repo-path=REPO_PATH]          # Path to a directory to scan.
                                       # Default: ./repo
      [--no-colors], [--no-no-colors]  # Do not colorize output.
```

Maybe it could say specifically `# Point to local or remote configuration files. e.g. --config="file://path/to/salus.yaml"` (with `file://` instead of space).

Either way, thank you very much @nishils !!

**Comment by nishils** [comment]
Oh that's a good doc bug. Thanks for letting me know. I've went ahead and opened a new issue to get this fixed.
