### ISSUE TITLE
Github Action Integration

### ISSUE THREAD

**Issue by jsulinski** [coinbase/salus#82]
With Github Actions now available to everyone, it would be great to support running Salus as an action, similar to the CircleCI integration.

**Comment by jsulinski** [comment]
Knocked out a first draft today! It depends on the custom_info hash feature in 2.6.3. 

The major feature remaining is to add a comment to PRs with a summary of the results.

**Comment by nishils** [comment]
This is awesome! It just recently got added to my backlog to work on something like this!! I'm excited to see that PR come in

**Comment by jsulinski** [comment]
Github seems to require Actions to live in their own repo. 

Wasn't sure how to brand this due to the integration with securedevelopment.com, the UI we're building around Salus, so I just called it Federacy Salus Security Scan. 

https://github.com/marketplace/actions/federacy-salus-security-scan
https://github.com/federacy/scan-action

**Comment by jsulinski** [comment]
Hey @nishils, any thoughts on the branding? My goal is to not downplay Coinbase as the author of Salus, while clarifying that you're not responsible for the Github Action or SecureDevelopment. This also provides a place to tie in documentation specific to Federacy/SecureDevelopment. 

Another option is to release two Github Actions: 

- one that is branded Coinbase Salus and has no additional documentation/reference to SecureDevelopment
- one that is maybe branded Federacy/SecureDevelopment Scans (with or without the Salus reference) and includes documentation

**Comment by nishils** [comment]
Thanks for the ping! I was on vacation and missed this in my notifications.

I think if you mention it in your description like `Salus from Coinbase`, then that would be helpful.

As long as the word Salus is around and links back to this repo, then I think that is sufficient. Thanks for considering our side of it!

**Comment by jsulinski** [comment]
Sounds good! Will make these changes and release soon.

**Comment by jsulinski** [comment]
Okay, updated the copy to make it more clear. Just let me know if you'd like me to add some documentation to the salus repo, otherwise we can close this issue!

**Comment by nishils** [comment]
Sorry for the delay on this. Can we add docs to this repo on how to get the github action configured?

**Comment by jsulinski** [comment]
Hey @nishils. No problem, I'll work on this soon.

**Comment by jsulinski** [comment]
https://github.com/coinbase/salus/pull/96

**Comment by jsulinski** [comment]
How does that look @nishils?

**Comment by xolaz** [comment]
looks great @jsulinski , thanks for making this! Closing the ticket now that it's resolved. 

fyi, getting a bad gateway error when trying to sign up on https://www.securedevelopment.com/sign-up

**Comment by jsulinski** [comment]
Should be fixed now. Thanks for letting me know!
