### ISSUE TITLE
Golang 1.13 support

### ISSUE THREAD

**Issue by Piccirello** [coinbase/salus#93]
I have an application that uses `os.UserConfigDir()`, which was introduced in golang 1.13. This is causing Salus to fail and report a Golang error: `"UserConfigDir not declared by package os"`. You can see an example build [here](https://github.com/DopplerHQ/cli/pull/59/checks?check_run_id=408473863). I'm using the federacy GitHub action to trigger salus. 

I see in the release notes for Salus 2.7.1 that golang 1.12.10 is currently used. Is there any way to force salus to use golang 1.13, disable building the golang code (I perform this action in another CI job), or some other solution? This is the last thing holding me back from merging the Salus CI job!

**Comment by nishils** [comment]
Hey @Piccirello,

Thanks for reporting this! We're looking at upgrading to golang 1.13 for the last few months but we constantly are running into compile errors on various projects that didn't exist in 1.12. We're looking into this more and will release a Salus build with an updated version.

Right now, I would fork the repo and modify the Dockerfile to pull in the 1.13 golang binary instead. You'll have to modify lines 47 and 49 in https://github.com/coinbase/salus/blob/master/Dockerfile#L47-L49. You may run into the same build issues as us or you may not. 1.13 has been flaky for us.

I know this isn't a great solution but should hopefully work for you.

**Comment by Piccirello** [comment]
Thanks a lot for the suggestion. I may hold off on this for now as it would require forking not only this repo but also the federacy GitHub Action. It may just be quicker in the short term to write a CI job that calls gosec (albeit w/o Salus' other goodies).

It would be great if the golang version were configurable. It would allow you to internally selectively build your failing projects with go 1.12, without having to hold back the default golang version. I completley understand if this feature isn't a priority.

One note on the Dockerfile you linked- there are a couple outdated dependencies. Node 12 is the [current](https://nodejs.org/en/) LTS version. The version of npm used is also quite a bit out of date. And lastly, gosec 2.1.0 is available 😃

**Comment by nishils** [comment]
Oh good point. We'll probably patch those this coming release.

I believe I got most of the gosec 2.1.0 features before they committed to a version bump by locking onto a recent commit.

We'll update these hopefully this week. The hard part is making sure we don't break existing projects in our integration tests and then figuring out why when we do .

Do you have an OSS project we can add to our integration tests that requires golang 1.13? We generally test these internally by running a diff between the latest and the dev branches before releasing.

**Comment by Piccirello** [comment]
> Do you have an OSS project we can add to our integration tests that requires golang 1.13?

You're welcome to use our [CLI](https://github.com/DopplerHQ/cli/) in your integration tests- it's OSS licensed with Apache 2.0. Otherwise, [this search](https://github.com/search?l=Go&q=%22os.UserConfigDir%22&type=Code) yielded a couple results using `os.UserConfigDir()`, including [OpenDiablo2/OpenDiablo2](https://github.com/OpenDiablo2/OpenDiablo2) with 4.5k stars.

**Comment by Piccirello** [comment]
Just a note that Go 1.14 has now been [released](https://tip.golang.org/doc/go1.14).

**Comment by nishils** [comment]
Hey @Piccirello 

We got this upgraded in 2.8.0.

Thanks!

**Comment by Piccirello** [comment]
Fantastic news! Thanks @nishils.
